version: '3.3'

services:
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    environment:
      - TZ=Europe/Moscow
      - LAST_TIME='/last_time.txt'
    volumes:
      - ./last_time.txt:/last_time.txt
    