version: '3.3'

services:
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Moscow
      - LAST_TIME=/last_time.txt
    volumes:
      - ./backend/last_time.txt:/last_time.txt
    
